# Generated by Django 5.1.7 on 2025-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_url',
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
