# Generated by Django 5.1.7 on 2025-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0003_remove_album_artist_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
