# Generated by Django 5.1.7 on 2025-05-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0004_alter_song_album_delete_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
