# Generated by Django 5.1.7 on 2025-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0005_remove_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
